### ISSUE TITLE
Arc line wavelength fitting for both Ne and Ar

### ISSUE THREAD

**Issue by dmkassis** [Keck-DataReductionPipelines/MosfireDRP#37] opened 2016-01-08 01:58 UTC
If both Ar and Ne lines are used in the wavelength fitting process, the RMS in the fits increases. The reason for the increased RMS is a 0.5 Angstrom shift between the wavelength solutions for the Ne and Ar lines. Using IRAF, I measured the residuals in the fit between Ar and Ne only (see the image). The image is from my note book and shows the residual plot from a wavelength fit of both Ar and Ne lines combined. There are two sets of residuals from Ne and Ar as indicated.
![img_0309](https://cloud.githubusercontent.com/assets/9427467/12187513/9cde34cc-b550-11e5-9e08-cc2b9c8fa16d.JPG). If you use only Ar or only Ne in the sky+arc solution with the MDRP, the residuals are smaller by about a factor of 10. Because of this offset between arcs of different lamps, it is necessary to find two arc lamp specific offsets first, apply those offsets, and then refit the combined line lists. 

I have been attempting to modify the code to accomplish this, but I have run into a snag. 
In Wavelength.py, there is a function def called "apply_lambda_sky_and_arc" which is used to merge the two sets of wavelength solutions from sky and arcs. I have attempted to modify this function. As I understand the code, it does the following:
1) generates a picket fence line list using the sky line solution
2) generates a picket fence line list using the arc line solution
3) Determines and applies a shift to the arc picket fence
4) splices the two picket fences, and this seems odd, by taking all of the short wavelegths of the sky line picket fence and taking all the longer wavelength arc picket fence to make one long list. 
5) refitting the spliced picket fence line list where the first half is sky list related and the second half is line list related.

From the original Wavelength.ph apply_lambda_sky_and_arc I think that the relevant code section is the following:
   for i in xrange(len(SkyL)):
        slp = SkyL[i]["2d"]["positions"].astype(np.int)
        slc = SkyL[i]["2d"]["coeffs"]
        slm = SkyL[i]["2d"]["lambdaMAD"]
        alp = ArcL[i]["2d"]["positions"].astype(np.int)
        alc = ArcL[i]["2d"]["coeffs"]
        alm = ArcL[i]["2d"]["lambdaMAD"]

```
    info("2d wavelengths: Slit %i/%i" % (i+1, len(SkyL)))

    prev = 0
    dpixels = []
    for j in xrange(len(slp)):

        if (slm[j] < 0.2) and (alm[j] < 0.2):

            coeff_sky = slc[j]
            coeff_arc = alc[j]
            lam_sky = CV.chebval(xx, coeff_sky)
            lam_arc = CV.chebval(xx, coeff_arc)

            # minimize pixel solution                                                                                   
            best_dpix = find_pixel_offset(lam_sky, coeff_arc, LROIs[i])
            dpixels.append(best_dpix)

            # Refit the chebyshev                                                                                       
            lambdas = CV.chebval(fitpix - best_dpix, coeff_arc)
            arc_positions = lambdas > np.mean(LROIs[i])
            sky_positions = lambdas <= np.mean(LROIs[i])

            to_fit = CV.chebval(fitpix[sky_positions], coeff_sky)
            to_fit = np.append(to_fit,
                CV.chebval(fitpix[arc_positions], coeff_arc))

            coeffs = CV.chebfit(fitpix, to_fit, options["chebyshev-degree"])


            prev = lams[slp[j],:] = CV.chebval(xx, coeffs)
            prevcoeff = coeffs
            SkyL[i]["2d"]["coeffs"][j,:] = coeffs
        else:
            lams[slp[j],:] = prev
```

---

Are we sure that this is correctly implemented? If it is, what is the best way to add in a third line list?

Here is the direction I was going, but I think this is the wrong way to go about this. I feel the shift should be applied to the original arc line list, and then the function refits for all lines (sky + (Ne shifted_ne)+ (Ar+shifted_ar)).

From my modified code that does not quite work yet:
        for j in xrange(len(slp)):

```
        if (slm[j] < 0.2) and (alm[j] < 0.2) and ( (arcnames2 == None) or (alm2[j] < 0.2)):

            coeff_sky = slc[j]
            coeff_arc = alc[j]
            lam_sky = CV.chebval(xx, coeff_sky)
            lam_arc = CV.chebval(xx, coeff_arc)

            # so we need to shift both Ar and Ne wavelength solutions                                                   
            # And I needt to keep track of both here.                                                                   

            # minimize pixel solution                                                                                   
            best_dpix = find_pixel_offset(lam_sky, coeff_arc, LROIs[i])
            dpixels.append(best_dpix)

            print "Value of bset_dpix:"
            print best_dpix


            if arcnames2 is not None:
                coeff_arc2 = alc2[j]
                lam_arc2 = CV.chebval(xx, coeff_arc2)
                best_dpix2 = find_pixel_offset(lam_sky, coeff_arc2, LROIs2[i])
                dpixels2.append(best_dpix2)
                print "Value of bset_dpix2:"
                print best_dpix2

            # Refit the chebyshev                                                                                       
            print "Fitpix - best_dpix"
            print fitpix - best_dpix
            lambdas = CV.chebval(fitpix - best_dpix, coeff_arc)
            print "Value for lambdas is:"
            print lambdas
            arc_positions = lambdas > np.mean(LROIs[i])
            sky_positions = lambdas <= np.mean(LROIs[i])
            print "Arc positions: "
            print arc_positions
            print "sky positions: "
            print sky_positions

            if arcnames2 is not None:
                lambdas2 = CV.chebval(fitpix - best_dpix2, coeff_arc2)
                arc_positions2 = lambdas > np.mean(LROIs2[i])
                sky_positions2 = lambdas <= np.mean(LROIs2[i])


            to_fit = CV.chebval(fitpix[sky_positions], coeff_sky)
            print "A- Length of variables are:"
            print len(fitpix)
            print len(to_fit)
            to_fit = np.append(to_fit, CV.chebval(fitpix[arc_positions], coeff_arc))

            if arcnames2 is not None:
                print "B- Length of variables are:"
                print len(fitpix)
                print len(to_fit)
                to_fit = np.append(to_fit,
                           CV.chebval(fitpix[arc_positions2], coeff_arc2))

            print "C-Length of variables are:"
            print len(fitpix)
            print len(to_fit)
            print to_fit

            coeffs = CV.chebfit(fitpix, to_fit, options["chebyshev-degree"])


            prev = lams[slp[j],:] = CV.chebval(xx, coeffs)
            prevcoeff = coeffs
            SkyL[i]["2d"]["coeffs"][j,:] = coeffs
        else:
            lams[slp[j],:] = prev
```

---

The above code does not work because of the dichotomy in the split seen here:
                arc_positions = lambdas > np.mean(LROIs[i])
                sky_positions = lambdas <= np.mean(LROIs[i])
In the current method, this has to be split three ways for sky, Ne, and Ar. I have not yet gone that direction because I am not convinced this is the correct method for combining the line lists now that I have had time to experiment with the code..

**Comment by csteidel** [comment] 2016-01-08 17:15
This issue has come up before, so I should reiterate that the DRP handling of arc line solutions was intended
only as a “kludge” to lock down the K-band arc solution longward of 2.3 microns, where the sky lines
are very sparse and weak- and really no one should ever use Ar for this purpose, as it is pretty useless
where it matters.  There was no case in which both Ar and Ne should be used together in the DRP, as
it would not have been handled properly.  

If one really wants to do full arc line solutions, I think the right way to do it is to construct a table of observed
line centroid (pixel) and nominal (not fitted) wavelength for each lamp observation (i.e., Ar , Ne), then merge those lists
into a sorted array of (pixel, nominal lambda) which is what should be handed to the fitting procedure (i.e., one
would not solve the lamp solution for a single lamp when both are desired, except to construct the
table/identify the lines that would go into it).  I think it’s probably important
to make the (pixel, lambda) identifications before (and not in the process of) doing the fitting— this
could use guesses from the sky solution or from one of the Ne or Ar solutions, but once the line peaks
are identified those initial fits used for feature identification should be discarded and replaced by
the fit to the full merged list.  My experience is that Ar does not yield good solutions by itself in K
band, but in combination with Ne it should. In other words, the array handed to the fitting procedure would
look like this:

    (529.35  , 19822.91)     where the first entry is the pixel centroid and the second is the **tabluated** wavelength (not the fitted wavelength) of the line identified
    (650.32   , 20355.77)
    ...

   In the above example, the first line is an Argon line, the second a Neon line, and they
 should be able to be sorted by pixel (or wavelength).
   
The result of this solution could then be compared with the sky line solution to obtain a single offset
of lamps vs. sky.   **There is no ostensible reason why there should be any shift between the arc solutions for Ar and
Ne lamps if the identifications of the lines are correct! **  

 Marc, why are you using a “spline3” function in IRAF in your plot?  This would definitely be a bad idea for
wavelength solutions since it forces the solution to go through all points in the list, rather than minimizing
the residuals.  If there really is a shift of 1 A between Ar and Ne I would suspect a problem with the
line IDs , the solution, or with the list itself.  I checked the DRP list and it should be correct for vaccum argon
wavelengths.

**Comment by dmkassis** [comment] 2016-01-08 19:25
I agree that there is not a clear reason why there is a shift between Ar and Ne. And maybe someone should verify that there is a shift between Ar and Ne arcs. For my quick check between Ar and Ne using IRAF, I used the default settings I had. I really only wanted to see a plot of the residuals to see if there was a dichotomy in the graph.

To confirm the offset between Ne and Ar, I used IDL to fit a 3 degree polynomial to the Ne lines and then used the know Ar lines to calculate the pixel location for those lines. The shift between Ar and Ne was 0.5 pixels. I did not write down in my notes what mask or slit I used for this calculation.  I have also modified the code to print what the measured shift between sky and arc and found that the MDRP finds a 0.15 +/- 0.05 pix shift between Ar and Ne lines for one of my masks (a smaller offset one that uses the sky lines as the reference).

I think that I have also simply added a constant offset to the Ar lines and fit with both the Ne and Ar and the residual values are on par with those when it is Neon only. I don’t see that test in my notes however.

Like you, I double checked the line IDs as well. Here is what I have found. Ne is taken from the observed column of the NIST database. It appears that the Ar list comes from ISAAC identifications. There are some differences at the level of 0.01 Angstroms, but I don’t think these should impact the fit.

Below is my table comparison:
MOSFIRE K band Ar line list

NIST database

NIRSPEC

ISAAC

19822.91

?

19822.92 - UK

Y

19971.18

?

ISAAC

Y

20322.56

RITZ-20322.6

ISAAC

Y

20574.43

?

?

Y

20621.86

Obs & RITZ

NIST

Y

20739.22

?

ISAAC

Y

20816.72

?

UK

Y

20991.84

Observed

NIST

Y

21338.71

RITZ

Outred, M.

Y

21540.09

RITZ-21540.08

21540.08-NIST

Y

22045.58

RITZ

NIST

Y

22083.21

RITZ

NIST

Y

23139.52

Observed-23139.51 & RITZ 23139.52

23139.51-NIST

Y

23851.54

RITZ

NIST

Y

23973.06

RITZ & observed

NIST

Y


I did circulate this wavelength comparison to the other SAs asking whether we should have a standard arc and sky reference list for all of our infrared instruments.

**Comment by csteidel** [comment] 2016-01-08 23:39
> On Jan 8, 2016, at 11:25 AM, Marc Kassis <notifications@github.com> wrote:
> 
> 
> To confirm the offset between Ne and Ar, I used IDL to fit a 3 degree polynomial to the Ne lines and then used the know Ar lines to calculate the pixel location for those lines. The shift between Ar and Ne was 0.5 pixels. I did not write down in my notes what mask or slit I used for this calculation. I have also modified the code to print what the measured shift between sky and arc and found that the MDRP finds a 0.15 +/- 0.05 pix shift between Ar and Ne lines for one of my masks (a smaller offset one that uses the sky lines as the reference). 

Marc- I think the shift looks like it is 0.5 A (as opposed to pixels); 

Just to verify, the arcs you are comparing were taken from exactly the same data set (i.e., quasi-simulataneously)?

The other possible issue is that the two fits are constrained in nearly disjoint ranges of wavelength, and it could
be that the Ne solution really is not a great predictor for Argon for this reason.  What kind of solution do you get if
you do it globally (as I described in my last thingy)? 

Another thing to watch out for:  switching between IDL and IRAF is potentially dangerous because
one uses zero index arrays (idl) and the other unity-index, so the meaning of “pixel” is different- possbily
relevant in predicting the position of Argon lines using the Neon solution

**Comment by dmkassis** [comment] 2016-01-09 00:03
The Ne and Ar arcs are from the same calibration sequence. Bars were not moved between arc data sets.

From my notes during the tests using the DRP

1)      Ne only STD= 0.03 MAD=0.02

2)      Ar only  STD=0.1 and MAD=0.5

3)      Removed faint Ar lines from the fit (20422,20574,20739, 20816) and adding line 23973.6 yeilds STD=0.02 MAD=0.03

a.       Notes here that a longer wavelength line was added to the fit

b.      The fainter lines were removed.

c.       In general the Ar lines are 10 times fainter than the Ne lines. Maybe increase the Ar exposure  time to fit more lines. Need to test.

4)      Combined Ne and Ar into one image via MDRP then used a combined Ne & Ar list (unsorted) . STD=0.5 and MAD=0.4.



5)      Combined the Ne and AR images by hand with IRAF imcombine and then used either Ne or Ar or both lines for fitting

a.       Ne STD=0.03 MAD=0.02

b.      Ar STD=0.04 MAD=0. 03

c.       Ne and Ar resulted in  STD=0.3 and MAD=0.5  10 times worse, Wacky!

It is at this point where I started examining the line lists and code looking for an explanation. In my tests I did not sort the list by pixel or wavelength.

**Comment by csteidel** [comment] 2016-01-09 00:22
Marc- I think it is important (based on my own experimentation with this during lab testing) to co-add images of Ne and Ar to do the fitting. There is enough blending of lines that occurs to throw the line centroids off enough to matter in the fits. The match of features to pixels must be done independently for each, and then the input is the merged *list of identified lines and their corresponding pixel positions* .
If that does not work without a shift of one with respect to another, then one last thing to check is whether the lamps are "symmetric" in the sense that there is no left-right imbalance of the illumination  for Argon vs. Neon.  It is *possible* that some difference in illumination that depends on exactly where the lamps are located and how much of each is masked could cause a small shift (for the same reason that internal lamps would be shifted wrt the night sky lines). Can you remind me what the lamp layout looks like in the front of the instrument?  If (e.g.) one of the lamps were burned out, its possible it could manifest itself in this way....

**Comment by csteidel** [comment] 2016-01-09 00:23
Sorry- just noticed that the first line above should read "It is important NOT to co-add images of Ne and Ar to do the fitting...."

**Comment by dmkassis** [comment] 2016-01-09 00:25
Understood. I don’t know the lamp positions, but I will ask our summit team to investigate.

**Comment by dmkassis** [comment] 2016-01-30 00:31
Chuck,

The summit techs looked at the lamp layout and found that Ar lamps are on the outside and Ne lamps are on the inside. Image 1438 shows the lamp positions. The bulbs with the ends uncovered by ¾ inch are the Ne lamps. The bulbs which look like they are completely covered are the Ar lamps (see image 1441).

Dwight indicated that the light from Ne comes from the ¾ inch exposed tip, while the light from the Ar lamp comes from the base close to the bulb socket. I am surprised that the Ar bulb bases were left exposed instead of the bulb tips, but I don’t think this explains what I observe.

Marc

**Closed** 2017-03-26 21:16 UTC
Labels: Wavelength
